Add build scan

diff --git a/.github/workflows/integrationTest.yml b/.github/workflows/integrationTest.yml
--- a/.github/workflows/integrationTest.yml
+++ b/.github/workflows/integrationTest.yml
@@ -19,11 +19,13 @@ jobs:
         uses: gradle/gradle-build-action@v2
 
       - name: Execute Gradle Integration Test
-        run: ./gradlew integrationTest
+        id: gradle
+        run: ./gradlew integrationTest --scan
 
-      - name: Archive integration test report
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: Integration test report
-          path: app/build/reports/tests/integrationTest
+
+#      - name: Archive integration test report
+#        uses: actions/upload-artifact@v3
+#        if: success() || failure()
+#        with:
+#          name: Integration test report
+#          path: app/build/reports/tests/integrationTest
